''' 
    JOGO PEDRA, PAPAL E TESOURA

JOGAR FUNÇÃO JOGAR
    DEFINIR OPÇÕES COMO LISTA COM ITENS: PEDRA, PAPEL, TES
    PERGUNTA JOGADOR QUAL SUA ESCOLHA: PEDRA, PAPEL OU TESOURA
    MAQUINA ESCOLHE PEDRA, PAPEL OU TESOURA ALEATORIAMENTE
    JOGADOR ESCOLHE PEDRA, PAPEL OU TESOURA

    SE JOGADOR ESCOLHER PEDRA E COMUPATADOR ESCOLHER TESOURA OU
    SE JOGADOR ESCOLHER PAPEL E COMPUTADOR ESCOLHER PEDRA OU
    SE JOGADOR ESCOLHER TESOURA E COMPUTADOR ESCOLHER PAPEL
        ENTÃO JOGADOR GANHA
    SENÃO SE JOGADOR FOR IGUAL AO COMPUTADOR
        ENTÃO EMPATE
    SENÃO
        COMPUTADOR GANHA

CHAMAR FUNÇÃO JOGAR
'''